### ISSUE TITLE
unusual console messages when first loading a web page with webworkers only configured in Program.cs

### ISSUE THREAD

**Issue by waleed-alharthi** [LostBeard/SpawnDev.BlazorJS#33]
**Describe the bug**
Blazor WASM resources appear as if loaded multiple times, as shown in the browser console, it previously only appears once:
```
dotnet Loaded 17.94 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller if you install wasm-tools workload. See also https://aka.ms/dotnet-wasm-features
```

Also, the current error appears when the page is first loaded, also twice:
```
blazor.webassembly.js:1  Error: One or more errors occurred. (Could not find 'synchronizeDbWithCache' ('synchronizeDbWithCache' was undefined).
Error: Could not find 'synchronizeDbWithCache' ('synchronizeDbWithCache' was undefined).
    at http://localhost/_framework/blazor.webassembly.js:1:368
    at Array.forEach (<anonymous>)
    at l.findFunction (http://localhost/_framework/blazor.webassembly.js:1:336)
    at w (http://localhost/_framework/blazor.webassembly.js:1:5079)
    at http://localhost/_framework/blazor.webassembly.js:1:2872
    at new Promise (<anonymous>)
    at b.beginInvokeJSFromDotNet (http://localhost/_framework/blazor.webassembly.js:1:2835)
    at Object.vn [as invokeJSJson] (http://localhost/_framework/blazor.webassembly.js:1:58849)
    at http://localhost/_framework/dotnet.runtime.8.0.5.gongq8hbow.js:3:178364
    at Tl (http://localhost/_framework/dotnet.runtime.8.0.5.gongq8hbow.js:3:179198))
    at Jn (http://localhost/_framework/dotnet.runtime.8.0.5.gongq8hbow.js:3:31614)
    at Tl (http://localhost/_framework/dotnet.runtime.8.0.5.gongq8hbow.js:3:182415)
    at do_icall (wasm://wasm/03f7fb96:wasm-function[2658]:0xd6e5a)
    at do_icall_wrapper (wasm://wasm/03f7fb96:wasm-function[2543]:0xd1dce)
    at mono_interp_exec_method (wasm://wasm/03f7fb96:wasm-function[2536]:0xc3cfc)
    at interp_entry (wasm://wasm/03f7fb96:wasm-function[2612]:0xd51f2)
    at interp_entry_static_0 (wasm://wasm/03f7fb96:wasm-function[2634]:0xd5cb6)
    at wasm_native_to_interp_System_Private_CoreLib_ThreadPool_BackgroundJobHandler (wasm://wasm/03f7fb96:wasm-function[16013]:0x35ed45)
    at mono_background_exec (wasm://wasm/03f7fb96:wasm-function[3547]:0x1074b9)
    at e.<computed> (http://localhost/_framework/dotnet.runtime.8.0.5.gongq8hbow.js:3:215551)
```

Other than those messages, the page actually loads and functions as normal.

**To Reproduce**
- Started with a Blazor .Net 7 (WASM+ASP.NET Core) hosted app.
- Upgraded app to .Net 8.
- Followed the steps in README.md to add SpawnDev.BlazorJS.WebWorkers in program.cs

**Expected behavior**
- No duplicate information messages.
- No error messages.

**Screenshots**
![image](https://github.com/LostBeard/SpawnDev.BlazorJS/assets/71645462/645b9d7e-c4e2-4773-89cd-511db59c214f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: MS Edge
 - Version: MS Edge 124.0.2478.97 (Official build) (64-bit)

**Comment by waleed-alharthi** [comment]
The same error `('synchronizeDbWithCache' was undefined)` appears and looks like the code just quits at line:
`var webWorker = await _webWorkerService.GetWebWorker();`
No exception message or anything.

```
public async Task<List<object>> GetToListAsync(Type entityType, CancellationToken cancellationToken = default, bool doSync = true)
{
    if (doSync)
    {
        //_listenerService.TriggerSyncStart(entityType);
        //await _syncService.SyncRemoteWithLocal(entityType, cancellationToken);
        Console.WriteLine("Getting ISyncService from _webWorkerService.TaskPool.GetService<ISyncService>()");
        var webWorker = await _webWorkerService.GetWebWorker();
        Console.WriteLine($"Got WebWorker instance Id {webWorker?.LocalInfo.InstanceId}");
        var service = webWorker.GetService<ISyncService>();
        Console.WriteLine($"Got ISyncService from _webWorkerService.TaskPool.GetService<ISyncService>() instance Id {_webWorkerService.InstanceId}");
        await service.SyncRemoteWithLocal(entityType, cancellationToken);
        Console.WriteLine("Finished SyncRemoteWithLocal using _webWorkerService.TaskPool.GetService<ISyncService>()");
    }
    return await _unitOfWork.GetListAsync(entityType,cancellationToken);
}
```

I'm likely missing something but can't figure it out!

**Comment by LostBeard** [comment]
Please include the contents of the ```Program.cs``` and ```*.csproj.``` from the Blazor WASM project that is having the issue.

None of those errors mention anything related to ```SpawnDev.BlazorJS.WebWorkers```. It is possible the issue is related to (possibly a conflict with) something else you are using.

> Expected behavior
> - No duplicate information messages.

You are using the package ```SpawnDev.BlazorJS.WebWorkers``` which uses [Workers](https://developer.mozilla.org/en-US/docs/Web/API/Worker) for multi-threading. When a new worker starts up, it is starting your Blazor WASM app in a worker, which outputs to the console of your Window scope. You are seeing those workers starting up.

**Comment by waleed-alharthi** [comment]
Searching the entire solution for `synchronizeDbWithCache` returned no results.
Maybe the besql library is not happy to start in a web worker mode.

I also tried updating to the latest Nuget package 2.2.98.

This is my .sln and files from Visual Studio, the main configuration runs with a docker-compose project so it may be a hassle to run unless you already develop on docker.
[RihalDotnetTemplateWasm.zip](https://github.com/LostBeard/SpawnDev.BlazorJS/files/15339343/RihalDotnetTemplateWasm.zip)

index.html
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>RihalDotnetTemplateWasm</title>
    <base href="/" />
    <link href="css/app.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="favicon.png" />
    <link href="RihalDotnetTemplateWasm.Client.styles.css" rel="stylesheet" />
    <link href="manifest.json" rel="manifest" />
    <link rel="apple-touch-icon" sizes="512x512" href="icon-512.png" />
    <link rel="apple-touch-icon" sizes="192x192" href="icon-192.png" />

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <link href="_content/MudBlazor/MudBlazor.min.css" rel="stylesheet" />
    <link href="_content/Z.Blazor.Diagrams/style.min.css" rel="stylesheet" />
    <link href="_content/Z.Blazor.Diagrams/default.styles.min.css" rel="stylesheet" />
</head>

<body>
    <div id="app">
        <svg class="loading-progress">
            <circle r="40%" cx="50%" cy="50%" />
            <circle r="40%" cx="50%" cy="50%" />
        </svg>
        <div class="loading-progress-text"></div>
    </div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>
    <script>navigator.serviceWorker.register('service-worker.js');</script>
    <script src="site.js"></script>
    <script src="_content/MudBlazor/MudBlazor.min.js"></script>
    <script src="_content/Z.Blazor.Diagrams/script.min.js"></script>
    <script src="_content/Bit.Besql/bit-besql.js"></script>
</body>

</html>
```

service-worker.js
```
self.addEventListener('fetch', () => { });
```

service-worker.published.js
```
// Caution! Be sure you understand the caveats before publishing an application with
// offline support. See https://aka.ms/blazor-offline-considerations

self.importScripts('./service-worker-assets.js');
self.addEventListener('install', event => event.waitUntil(onInstall(event)));
self.addEventListener('activate', event => event.waitUntil(onActivate(event)));
self.addEventListener('fetch', event => event.respondWith(onFetch(event)));

const cacheNamePrefix = 'offline-cache-';
const cacheName = `${cacheNamePrefix}${self.assetsManifest.version}`;
const offlineAssetsInclude = [ /\.dll$/, /\.pdb$/, /\.wasm/, /\.html/, /\.js$/, /\.json$/, /\.css$/, /\.woff$/, /\.png$/, /\.jpe?g$/, /\.gif$/, /\.ico$/, /\.blat$/, /\.dat$/ ];
const offlineAssetsExclude = [ /^service-worker\.js$/ ];

async function onInstall(event) {
    console.info('Service worker: Install');

    // Fetch and cache all matching items from the assets manifest
    const assetsRequests = self.assetsManifest.assets
        .filter(asset => offlineAssetsInclude.some(pattern => pattern.test(asset.url)))
        .filter(asset => !offlineAssetsExclude.some(pattern => pattern.test(asset.url)))
        .map(asset => new Request(asset.url, { integrity: asset.hash, cache: 'no-cache' }));
    await caches.open(cacheName).then(cache => cache.addAll(assetsRequests));
}

async function onActivate(event) {
    console.info('Service worker: Activate');

    // Delete unused caches
    const cacheKeys = await caches.keys();
    await Promise.all(cacheKeys
        .filter(key => key.startsWith(cacheNamePrefix) && key !== cacheName)
        .map(key => caches.delete(key)));
}

async function onFetch(event) {
    let cachedResponse = null;
    if (event.request.method === 'GET') {
        // For all navigation requests, try to serve index.html from cache
        // If you need some URLs to be server-rendered, edit the following check to exclude those URLs
        const shouldServeIndexHtml = event.request.mode === 'navigate';

        const request = shouldServeIndexHtml ? 'index.html' : event.request;
        const cache = await caches.open(cacheName);
        cachedResponse = await cache.match(request);
    }

    return cachedResponse || fetch(event.request);
}
```

**Comment by LostBeard** [comment]
> Maybe the besql library is not happy to start in a web worker mode.

That is probably very close to true. Its Javascript script was not being loaded at all in your workers. Loading scripts from your index.html into web workers is opt in, in part, due to the likeliness of compatibility issues with most scripts. 
[Javascript dependencies in WebWorkers
](https://github.com/LostBeard/SpawnDev.BlazorJS?tab=readme-ov-file#javascript-dependencies-in-webworkers)

Minor change to your index.html to enable the Besql script in web workers. You may need to enable other scripts as needed.
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>RihalDotnetTemplateWasm</title>
    <base href="/" />
    <link href="css/app.css" rel="stylesheet" />
    <link rel="icon" type="image/png" href="favicon.png" />
    <link href="RihalDotnetTemplateWasm.Client.styles.css" rel="stylesheet" />
    <link href="manifest.json" rel="manifest" />
    <link rel="apple-touch-icon" sizes="512x512" href="icon-512.png" />
    <link rel="apple-touch-icon" sizes="192x192" href="icon-192.png" />

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <link href="_content/MudBlazor/MudBlazor.min.css" rel="stylesheet" />
    <link href="_content/Z.Blazor.Diagrams/style.min.css" rel="stylesheet" />
    <link href="_content/Z.Blazor.Diagrams/default.styles.min.css" rel="stylesheet" />
</head>

<body>
    <div id="app">
        <svg class="loading-progress">
            <circle r="40%" cx="50%" cy="50%" />
            <circle r="40%" cx="50%" cy="50%" />
        </svg>
        <div class="loading-progress-text"></div>
    </div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>
    <script src="_framework/blazor.webassembly.js"></script>
    <script>navigator.serviceWorker.register('service-worker.js');</script>
    <script src="site.js"></script>
    <script src="_content/MudBlazor/MudBlazor.min.js"></script>
    <script src="_content/Z.Blazor.Diagrams/script.min.js"></script>
    <script webworker-enabled  src="_content/Bit.Besql/bit-besql.js"></script>
</body>

</html>
```

**Comment by LostBeard** [comment]
While looking at your ```Program.cs``` I saw the below line which I believe is unnecessary, and may cause other issues.

```cs
builder.Services.RegisterServiceWorker<SyncServiceWorker>();
```

That line registers a copy of your Blazor app to run as the service worker with an instance of ```SyncServiceWorker``` that will handle service worker events, but the rest of your setup conflicts with that setup. However, it looks like you want a Javascript ServiceWorker (which you provided code for above) instead. If that is the case you should remove the line above from your ```Program.cs```.

**Comment by waleed-alharthi** [comment]
This magical line `webworker-enabled` solved the main issue. The db error no long appears when first loading the page. Now I'm getting stackoverflow exception when syncing the data but that's probably something else.

I completely missed the JavaScript dependencies section.

As for the Service Worker that was an experiment when I failed to get Web Workers running. I'll remove it.

I'll investigate the cause of the new error and submit a fresh issue if it's relevant. Many thanks for your help!
